name: Gated pull request
on:
    workflow_dispatch:
    pull_request:
        branches: [master]
jobs:
    build-and-test:
        runs-on: windows-latest
        permissions:
            contents: read
            actions: read
            checks: write
        steps:
            - name: checkout
              uses: actions/checkout@v5
            - name: setup node
              uses: actions/setup-node@v5
              with:
                  node-version-file: "package.json"
            - run: node -v
            - run: npm ci
            - run: npm audit
            - run: npm run build
            - name: Run tests
              run: npm run test > test-output.txt 2>&1
              continue-on-error: true
            - name: Create test summary
              if: always()
              run: |
                  echo "## Test Results" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  Get-Content test-output.txt | Select-Object -Last 10 >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
              shell: pwsh
            - name: Publish test results
              uses: dorny/test-reporter@v2.1.1
              if: success() || failure()
              with:
                  name: Mocha Tests
                  path: test-results.xml
                  reporter: java-junit
                  fail-on-error: true
