name: Gated pull request
on:
    workflow_dispatch:
    pull_request:
        branches: [master]
jobs:
    build-and-test:
        runs-on: windows-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5
            - name: setup node
              uses: actions/setup-node@v5
              with:
                  node-version-file: "package.json"
            - run: node -v
            - run: npm ci
            - run: npm audit
            - run: npm run build
            - run: npm run test
